---
- name: Generate and disribute keys
  vars:
    user: ubuntu
  hosts: localhost
  tasks:
    - name: Generate key
      shell:
        cmd: ssh-keygen -q -t rsa -N '' -f ~/.ssh/id_rsa 2>/dev/null <<< y >/dev/null 

    - name: Distribute key
      shell:
        cmd: cat ~/.ssh/id_rsa.pub | ssh -i aws-key.pem {{ user }}@{{ item }} "cat >> ~/.ssh/authorized_keys"
      with_items:
