---
- name: Create Infra for K8-cluster
  hosts: localhost
  gather_facts: False
  vars:
    keypair: aws-key
    instance_type: t2.micro
    security_group: default
    image: ami-0eb89db7593b5d434
    region: eu-west-2
    subnet: subnet-082213e51ccfdcaa4 
  tasks:
    - name: Launch master instance
      ec2:
         key_name: "{{ keypair }}"
         group: "{{ security_group }}"
         instance_type: "{{ instance_type }}"
         image: "{{ image }}"
         user_data: "{{ lookup('file', 'user_data') }}"
         wait: true
         region: "{{ region }}"
         vpc_subnet_id: "{{ subnet }}"
         assign_public_ip: yes
      register: ec2
    - name: Adding tags to the EC2 Instance"
         local_action: ec2_tag
                      region={{ region }}
                      resource={{ item.id }}
                      state=present
         with_items: ec2.instances
         args:
           tags:
             node-type: master
             Name: Master
      register: tag
    - name: Launch worker instance
      ec2:
         count: 2
         key_name: "{{ keypair }}"
         group: "{{ security_group }}"
         instance_type: "{{ instance_type }}"
         image: "{{ image }}"
         user_data: "{{ lookup('file', 'user_data') }}"
         wait: true
         region: "{{ region }}"
         vpc_subnet_id: "{{ subnet }}"
         assign_public_ip: yes
      register: ec2
    - name: Adding tags to the EC2 Instance"
         local_action: ec2_tag
                      region={{ region }}
                      resource={{ item.id }}
                      state=present
         with_items: ec2.instances
         args:
           tags:
             node-type: worker
             Name: worker-{{ count }}
      register: tag
 
